const ViewManagerActionsConstants = {
    SAVE_TASK: 'SAVE_TASK',
    FETCH_SUBORDINATES: 'FETCH_SUBORDINATES',
    FETCH_SUBORDINATES_SUCCESS: 'FETCH_SUBORDINATES_SUCCESS',
    FETCH_SUBORDINATES_FAIL: 'FETCH_SUBORDINATES_FAIL',
    FETCH_REPORTS: 'FETCH_REPORTS',
    FETCH_REPORTS_SUCCESS: 'FETCH_REPORTS_SUCCESS',
    FETCH_REPORTS_FAIL: 'FETCH_REPORTS_FAIL'

}

export { ViewManagerActionsConstants }