
const EmployeeListActionsConstants = {
    FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
    FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAIL: 'FETCH_EMPLOYEES_FAIL',
    FETCH_MANAGERS: 'FETCH_MANAGERS',
    FETCH_MANAGERS_SUCCESS: 'FETCH_MANAGERS_SUCCESS',
    FETCH_MANAGERS_FAIL: 'FETCH_MANAGERS_FAIL'
    
}

export { EmployeeListActionsConstants }